src/App.js, src/App.test.js, src/UserApp.js, src/components/DeleteCurrentUserView.js, src/components/GroupGrid.js, src/components/RoleGrid.js, src/components/SectionLoader.js, src/components/SideNav.js, src/components/UserGrid.js, src/index.js, src/store.js
- d2 can be pulled into the context of each component
- app is wrapped in REDUX store provider
- Basic section routing implemented via d2-ui sidebar
=> Basic app skeleton:

src/api/utils.js, src/constants/queryFields.js, src/containers/UserForm/validate.js, src/selectors/index.js
I was blissfully unaware of the fact that users can have attributeValues, so I have now added support for that.
=> Fetch attributeValues from server and append them to saveData

src/utils/validators.js
- See [the JIRA issue](https://jira.dhis2.org/browse/DHIS2-6730) for more context. 
- I am keeping this as a draft PR for now, because the fix should not be deployed until the analogue issue in the `user-profile-app` has been resolved too.
=> fix(password): special character validation now aligned with server (DHIS2-6493)

src/index.js
First init d2 with correct baseUrl, then call getUserSetting
=> fix(d2): first init d2 with correct baseUrl, then call getUserSettings

src/utils/validators.js
DO NOT MERGE!!!!!
We have a code-freeze on this branch at the moment
=> fix(user-form): allow uppercase email addresses (V33 BACKPORT)

i18n/en.pot, src/constants/routeConfig.js, src/locales/en/translations.json
=> fix: typo on user section and make translatable (DHIS2-7638) (V31)

src/components/ReplicateUserForm.js, src/containers/GroupForm/GroupForm.js, src/containers/RoleForm/RoleForm.js, src/containers/UserForm/UserForm.js, src/containers/UserForm/config.js
If you like to, see https://dhis2.slack.com/archives/G451J9KGR/p1569936147060900 for some context...
=> fix(forms): prevent autocomplete

src/components/List/List.js
https://jira.dhis2.org/browse/DHIS2-8099
=> fix: add margin below list to avoid [+] button overlapping pagination

package.json, yarn.lock
=> fix(translation): prevent JS error in list view for Indonesian language

src/components/SearchableOrgUnitTree.js, src/containers/UserForm/collectValidators.js, src/containers/UserForm/config.js, src/utils/fieldRenderers.js
This isn't the prettiest way to show errors but at least it's identical to how I do it in the group-editor
=> fix(user-form): make data capture and maintenance org unit mandatory

i18n/en.pot, src/api/index.js, src/components/List/List.js, src/containers/GroupList/GroupList.js, src/selectors/index.js, src/utils/detectCurrentUserChanges.js
=> fix: don't fetch unpaged members of current user groups (DHIS2-103770) (v35)

i18n/en.pot, src/api/index.js, src/components/List/List.js, src/containers/GroupList/GroupList.js, src/selectors/index.js, src/utils/detectCurrentUserChanges.js
=> fix: don't fetch unpaged members of current user groups (DHIS2-10377) (v34)

i18n/en.pot, src/api/index.js, src/constants/queryFields.js, src/containers/GroupForm/GroupForm.js, src/containers/GroupForm/collectValidators.js, src/containers/GroupForm/config.js
=> fix(user-group): remove users field from form to prevent app freezing

i18n/en.pot, src/api/utils.js, src/constants/queryFields.js, src/containers/UserForm/config.js, src/selectors/index.js, src/utils/fieldRenderers.js
Fixes [DHIS2-10364](https://jira.dhis2.org/browse/DHIS2-10364)
* Adds a date field
* Displays the date field in the user new & edit form
=> feat(user form): add account expiry date field (edit & new)

src/utils/validators.js
I decided to use the same regex as we use in ui-forms, since that has pretty decent test coverage.
=> fix(user): improve regex for email validation (DHIS2-4527)

src/selectors/index.js
=> fix(expiry date): do not parse empty initial state to date

package.json, yarn.lock
Backport of #784 
Fixes a service worker issue: https://jira.dhis2.org/browse/DHIS2-11487
=> fix: bump cli-app-scripts to 7.1.0 (v36)

i18n/en.pot, src/constants/detailFieldConfigs.js, src/containers/UserForm/config.js
Closes https://jira.dhis2.org/browse/DHIS2-11866
=> fix: rename 'surname' field to 'last name' and show after 'first name' field

i18n/en.pot, src/components/AuthorityEditor/AuthorityFilter.js, src/components/AuthorityEditor/AuthorityGroup.js, src/components/AuthorityEditor/AuthorityItem.js, src/components/AuthorityEditor/AuthoritySection.js, src/components/AuthorityEditor/AuthoritySection.module.css, src/components/AuthorityEditor/FilteredAuthoritySections.js, src/components/AuthorityEditor/style.css, src/components/AuthorityEditor/utils/groupAuthorities.js, src/components/SearchableGroupEditor.js, yarn.lock
Closes https://jira.dhis2.org/browse/DHIS2-11853 and DHIS2-11825 (once `beta` is merged into `master`)
=>  feat: migrate user-group form to dhis2/ui

package.json, yarn.lock
Use latest plugins/commands with fix in internal `getFeatureName` util
=> chore: upgrade to cypress commands and plugins v9

src/constants/defaults.js, src/constants/queryFields.js, src/containers/UserForm/config.js
I forgot to backport this issue quite some time ago.
=> fix(user): add disabled field to user form (DHIS2-7940) (v35)

src/utils/validators.js
I forgot to backport this issue quite some time ago.
=> fix(user): improve regex for email validation (DHIS2-4527)  (v35)

src/components/UserForm/getUserData.js, src/pages/UserList/UserList.js
Fixes:
- [Stringify array of organisation units before passing to a refetch useEffect, fixing an infinite request loop](https://github.com/dhis2/user-app/commit/6fcfedb4d897f7550ac972d116aa6d44007ef525)
- Frontend fix for https://jira.dhis2.org/browse/DHIS2-12705 in case backend fix not implemented in time for soft freeze
=> fix(user): org unit related fixes

src/components/Form.module.css
Closes https://jira.dhis2.org/browse/DHIS2-12767
| Before | After |
| --------- | ------ |
| ![image](https://user-images.githubusercontent.com/4295266/157243294-05da1298-b169-40bd-beb9-985624d8d804.png) | ![image](https://user-images.githubusercontent.com/4295266/157243236-2611c639-2218-4bea-8873-036315d546ba.png) |
=> fix(form): increase width of date input types due to Chrome calendar icon

src/components/Form.module.css
v38 backport of https://github.com/dhis2/user-app/pull/914
=> fix(form): increase width of date input types due to Chrome calendar icon (v38)

src/pages/GroupList/ContextMenu/Modals/LeaveModal.js
Closes https://jira.dhis2.org/browse/DHIS2-12771
=> fix(groups): use correct method and endpoint to leave groups

src/pages/GroupList/ContextMenu/Modals/LeaveModal.js
v38 backport of https://github.com/dhis2/user-app/pull/912
=> fix(groups): use correct method and endpoint to leave groups (v38)

src/components/UserForm/BasicInformationSection.js
2.38.0 backport of https://github.com/dhis2/user-app/pull/917
:heavy_check_mark: Approved by RCB
=> fix(user): show user's database language (2.38.0)

src/components/UserForm/BasicInformationSection.js
v38 backport of https://github.com/dhis2/user-app/pull/917
=> fix(user): show user's database language (v38)

src/components/UserForm/BasicInformationSection.js
Closes https://jira.dhis2.org/browse/DHIS2-12877
=> fix(user): show user's database language

src/attributes.js
v38 backport of https://github.com/dhis2/user-app/pull/927
=> fix(attributes): don't assume presence of values.attributeValues (v38)

src/attributes.js
2.38.0 backport of https://github.com/dhis2/user-app/pull/927
:warning: Needs RCB approval
=> fix(attributes): don't assume presence of values.attributeValues (2.38.0)

src/pages/UserList/ContextMenu/Modals/ReplicateModal.js
v38 backport of https://github.com/dhis2/user-app/pull/925
=> fix(user-list): show title at top of 'replicate user' form (v38)

package.json, yarn.lock
=> fix: upgrade @dhis2/ui to allow lowercase in username validation (v38)

package.json, yarn.lock
v38 backport of https://github.com/dhis2/user-app/pull/1051
=> fix: upgrade @dhis2/ui to use correct username validation (v38)

package.json, yarn.lock
path/2.39.0 backport of https://github.com/dhis2/user-app/pull/1051
=> fix: upgrade @dhis2/ui to use correct username validation (patch 2.39.0)

src/pages/UserList/select/menu-wrapper.js
Fix for https://dhis2.atlassian.net/browse/DHIS2-13865
=> fix(styled-jsx): remove incorrect extension

src/components/BulkMemberManager/BulkMemberManager.js, src/components/BulkMemberManager/ResultsTable/ResultsTable.js, src/components/BulkMemberManager/hooks/useResults/useResults.js
v39 backport of https://github.com/dhis2/user-app/pull/1073
=> fix: user manager checkbox behaviour [DHIS2-13914] (v39)

src/components/UserForm/validators.js, src/pages/UserList/ContextMenu/Modals/ReplicateModal.js, src/pages/UserList/UserTable.test.js
Backport of https://github.com/dhis2/user-app/pull/1092
=> fix: use dedicated endpoint for checking the username [DHIS2-14147] (v39)

src/components/UserForm/validators.js, src/pages/UserList/ContextMenu/Modals/ReplicateModal.js, src/pages/UserList/UserTable.test.js
v38 backport of https://github.com/dhis2/user-app/pull/1092/
=> fix: use dedicated endpoint for checking the username [DHIS2-14147] (v38)

package.json, src/pages/UserList/UserTable.js, yarn.lock
See [DHIS2-14203)](https://dhis2.atlassian.net/browse/DHIS2-14203)
Note: this fix uses app-runtime 3.8.0 with new useTimeZoneConversion hook
**Precondition:** _(I'm using the app in Tokyo, but my server is in Oslo). A user has just logged in 4 minutes ago and I should see this relative timestamp in the UserList table_
**Before:**
Shows as 8 hours ago
**After:**
Shows as 4 minutes ago
=> fix: update lastLogin for server difference [DHIS2-14203]

src/pages/UserList/useFilters.js
v38 backport of https://github.com/dhis2/user-app/pull/1100
=> fix: clear self registration select on filter reset [DHIS2-14189] v39

src/pages/UserList/useFilters.js
v39 backport of https://github.com/dhis2/user-app/pull/1100
=> fix: clear self registration select on filter reset [DHIS2-14189] v38

package.json, src/pages/UserList/UserTable.js, yarn.lock
backport for https://github.com/dhis2/user-app/pull/1118
=> fix: last login time [DHIS2-14203] (2.38)

package.json, src/pages/UserList/UserTable.js, yarn.lock
backport for https://github.com/dhis2/user-app/pull/1118
=> fix: last login time [DHIS2-14203] (2.39)

src/pages/UserList/ContextMenu/Modals/ReplicateModal.js, src/pages/UserList/ContextMenu/Modals/ReplicateModal.module.css
Backport of https://github.com/dhis2/user-app/pull/1293
=> fix: hide x scrollbar in replicate user [DHIS2-15611] v38

src/pages/UserList/ContextMenu/Modals/ReplicateModal.js, src/pages/UserList/ContextMenu/Modals/ReplicateModal.module.css
Backport of https://github.com/dhis2/user-app/pull/1293
=> fix: hide x scrollbar in replicate user [DHIS2-15611] v39

src/pages/UserList/ContextMenu/Modals/ReplicateModal.js, src/pages/UserList/ContextMenu/Modals/ReplicateModal.module.css
Backport of https://github.com/dhis2/user-app/pull/1293
=> fix: hide x scrollbar in replicate user [DHIS2-15611] v40

src/components/SearchableOrgUnitTree/AsyncAutoComplete/useOrgUnitSearchResults.js
Backport of https://github.com/dhis2/user-app/pull/1217
=> fix: org unit search logic [DHIS2-14585] v39

src/components/SearchableOrgUnitTree/AsyncAutoComplete/useOrgUnitSearchResults.js
Backport of https://github.com/dhis2/user-app/pull/1217
=> fix: org unit search logic [DHIS2-14585] v38

src/pages/UserList/ContextMenu/Modals/DisableModal.js, src/pages/UserList/ContextMenu/Modals/EnableModal.js
forwardport of https://github.com/dhis2/user-app/pull/1264
(fix was relevant only for v38 and v39 and was first made on v38 because the issue was reported for v38)
=> fix: enable disable functionality [DHIS2-15512] v39

src/components/UserForm/SecuritySection.js
Backport of https://github.com/dhis2/user-app/pull/1131
=> fix: align password help text with validation logic [DHIS2-15485] (v38)

src/components/UserForm/SecuritySection.js
Backport of https://github.com/dhis2/user-app/pull/1131
=> fix: align password help text with validation logic [DHIS2-15485] (v40) 

src/components/UserForm/SecuritySection.js
Backport of https://github.com/dhis2/user-app/pull/1131
=> fix: align password help text with validation logic [DHIS2-15485] (v39)

src/components/UserForm/RolesSection.js
Backport of https://github.com/dhis2/user-app/pull/1215
=> fix: handle empty user roles response [DHIS2-15368] (v40)

src/components/UserForm/RolesSection.js
Backport of https://github.com/dhis2/user-app/pull/1215
=> fix: handle empty user roles response [DHIS2-15368] (v39)

src/components/UserForm/RolesSection.js
Backport of https://github.com/dhis2/user-app/pull/1215
=> fix: handle empty user roles response [DHIS2-15368] (v38)

src/pages/UserList/ContextMenu/Modals/Disable2FaModal.js
See https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-15866
Updates v39 version of user app to use correct endpoint for disabling 2fa.
=> fix: update api for 2fa disable [DHIS2-15866]

src/AppWrapper.js, src/components/Form.js, src/components/GroupForm/GroupForm.js, src/components/RoleForm/RoleForm.js, src/components/UserForm/UserForm.js, src/pages/GroupList/ContextMenu/ContextMenu.js, src/pages/GroupList/GroupTable.js, src/pages/RoleList/ContextMenu/ContextMenu.js, src/pages/RoleList/RoleTable.js, src/pages/UserList/ContextMenu/ContextMenu.js, src/pages/UserList/UserTable.js, src/providers/ReferrerContext.js, src/providers/ReferrerProvider.js, src/providers/index.js, src/providers/useReferrer.js, src/utils/navigateTo.js
Backport for v40 of https://github.com/dhis2/user-app/pull/1218
=> fix: update successful save redirects [DHIS2-15431] (#1218)

src/components/SearchableOrgUnitTree/AsyncAutoComplete/getRestrictedOrgUnits.js, src/components/SearchableOrgUnitTree/AsyncAutoComplete/getRestrictedOrgUnits.test.js
Backport of https://github.com/dhis2/user-app/pull/1324
=> fix: org unit access in search [DHIS2-16268] (v40)

src/components/RoleForm/groupAuthorities/groupAuthorities.js
backporting https://github.com/dhis2/user-app/pull/1422
=> fix: ignore case when sorting grouped authorities by name (v40)

src/components/RoleForm/groupAuthorities/groupAuthorities.js
backporting https://github.com/dhis2/user-app/pull/1422
=> fix: ignore case when sorting grouped authorities by name (v39)

src/components/RoleForm/groupAuthorities/groupAuthorities.js
v40 backport of https://github.com/dhis2/user-app/pull/1428
=> fix: add capture authority to tracker list (v40)

.github/workflows/dhis2-preview-pr.yml, .github/workflows/dhis2-verify-app.yml, .github/workflows/dhis2-verify-commits.yml
updates ci (see https://github.com/dhis2/user-app/pull/1551)
=> fix: release actions setup node patch 2-40-8

d2.config.js, i18n/en.pot, package.json, yarn.lock
Implements [DHIS2-20087](https://dhis2.atlassian.net/browse/DHIS2-20087)
-----
This PR adds shortcuts for 6 routes within the user app: `User`, `New User`, `User Roles`, `New User Role`, `User groups`, `New user group`.
------
- Run `yarn build` within the app directory. 
- Install the bundled app on a v42 instance either using the app management app or the cli. 
- Launch the command palette to check out the new shortcuts. 
- For this implementation, you can view the shortcuts [here](https://dev.im.dhis2.org/shortcuts-test/)
------
[DHIS2-20087]: https://dhis2.atlassian.net/browse/DHIS2-20087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add shortcuts to the command palette
