- src/api/index.js
- src/containers/RoleForm/RoleForm.js
- Roles were being saved by simply calling `role.save` (role being an instance of a d2 role model).
- This method expects that all arrays are populated by objects with this structure { id, <ID> }. If the authorities array would be a plain list of strings, d2 will send an empty array to the server.
- But if the authorities payload has this structure, the server will save the key "id" as an authority too. the server does expect a plain list of strings.
- So as a result of this discrepancy, saving now happens by calling post/update on the d2 API instance.
> Fixes issue that caused key "id" to be saved as an authority

- src/api/index.js
A problem I struggled with in the user-app, is the fact that it is also possible to change the current user, and its related user-groups and roles. This means the `d2.currentUser` model should be updated under certain circumstances and d2 doesn't simply offer a `d2.currentUser.reload()` method. So, I introduced some logic which creates a new currentUser instance and replaces the currentUser of my d2 instance with that.
However, there turned out to be two things wrong with my approach:
1. I was passing the wrong `userSettings` object to `CurrentUserClass.create`. I should have passed  `this.d2.currentUser.userSettings.settings` but I was passing `this.d2.currentUser.userSettings`. You can see why this was triggering lots of get requests [in this section of …
> Fix repeated GET requests after saving user that is also the current user

- src/api/utils.js
1) New users can't have any other properties than the ones defined in the form
2) When copying all owned properties from fresh d2 user-model instance, ModelCollections will be created for orgUnits and these can't be used in a payload directly
> Only copy owned properties for existing users

- src/containers/GroupForm/GroupForm.js
- src/selectors/index.js
- This bug was introduced in #39. 
- The Group form is now fetching some stuff at CDM and then setting the initial form values. 
- Before #39 it was setting the initialValues in `mapStateToProps` and the `asArray` helper returns an empty array for undefined values. 
- As a result the initial value for users and managed groups would be an empty array for new user-groups.
- The new setup uses a selector function which would only set initial values when editing a user group. So for new user-groups, the managed groups value would be undefined until the field was updated by the user. Not good, because this is an optional field
- So now, I am setting the initial values in the context of a new user-group too.
- And I've removed the section that would set the initial values in `mapStateToProps`. …
> Dhis2 5511 unable to create user group

- src/utils/fieldRenderers.js
- If an attribute is required to be unique, then these fields are added to the ReduxForm asyncBlurFields array
- Whenever a field in this array is blurred, the asyncValidator will run.
- However, the version of MUI SelectField in use is not firing a blur after an option is selected
- Prior to the introduction of attribute-fields into the user-app, there was no need to show error messages below SelectFields yet (no required fields were rendered as a dropdown, and invalid values were not possible)
- As a result, the field-renderer `renderSelectField` hadn't implemented displaying error messages
1. The field-renderer `renderSelectField` will now show an orange warning whilst validating, and a red error text when there is an error
2. After `onChange` is called on the input element, the …
> DHIS2-5556 Unique attributes rendered as DropDown

- src/utils/validators.js
This fixes a bug that would treat optional attribute values as mandatory. This would happen for most attribute valueTypes. Only if an input has a value, the input-value should be evaluated. If no value is present the pattern validators should classify the input-value as valid.
> fix(attribute validation): only validate patterns when fields have a value

- i18n/en.pot
- package.json
- src/containers/GroupForm/GroupForm.js
- src/containers/RoleForm/RoleForm.js
- src/locales/en/translations.json
- src/utils/validatorsAsync.js
- yarn.lock
The problem with redux-form is that for some reason, it seems to assume only one `asyncErrors` can exist at one time. So when throwing a new error, the previous error would be gone. Luckily, it is possible to access the existing `asyncErrors` prior to throwing new ones, so it was possible to just merge the existing and new ones into an object and throw that.
I also realised, when updating to redux-form v7.4.x from v7.2.x the entire async validation broke, so I decided to keep the upgrade and fix, because I don't like being stuck on an old version.
See commit message for detailed description of all changes.
> DHIS2-5604: Async field-validation-error cleared when running async validation on other field

- src/api/index.js
- src/selectors/index.js
Some background info:
- Previously, we encountered a situation where a superuser (having the `ALL` authority) had not been assigned to the root organisation. That user would be unable to manage users properly, because he could not access the whole OrgunitTree.
- To combat that, I introduced an exception in the `orgUnitRootsSelector` which would assign THE (as in only 1) OrgUnitRoot to users with the `ALL` authority
- Now it has come to light that it is possible to have organisations with multiple OrgUnitRoots...
Steps to test the fix:
1. Download [XML file](https://jira.dhis2.org/secure/attachment/13460/organisationUnits-dual_root_2.xml) from the issue description
2. Go to the import-export-app in your local dhis2-core instance and import the XML file (choose Metadata import and select …
> DHIS2-4659: User administration does not support multiple OU roots

- src/utils/validatorsAsync.js
These are fixes to the redux-form async-blur fields validation. There were two issues:
- First was a regression issue left after I upgraded of redux form. I was still resolving empty objects, which is what the previous version of redux form expected. In the current version everything worked fine, but I got an internal warning.
- Second the actual issue, which was that after clearing an attribute field that had an error, the function `getAttributeUniquenessError` would be called with an empty string, and the empty string would be checked for uniqueness on the server, which resulted in an error. So now I am just resolving if the value is falsy (L144-147)
> fix(form-validation): async blur fields clearing

- src/api/index.js
- src/api/utils.js
What was happening was the following:
- I was doing a query which, I thought, would only return users with a given value on a given attribute id
- But it turned out that it returned users that had ANY VALUE on a particular attribute ID, and matched the given value on ANY ATTRIBUTE
I didn't find any way to solve this by updating the query, so instead I added an extra check on the client.
> Fix unique attribute check

- i18n/en.pot
- src/components/AuthorityEditor/utils/authorityGroupNames.js
- src/components/AuthorityEditor/utils/groupAuthorities.js
- src/locales/en/translations.json
As you can see, this PR adds some configuration only:
- I've added a new authority key to the import/export section in `/utils/groupAuthorities.js`
- The rest is just translation stuff
And here is the result on screen:
> feat(authorities): adds skip-data-import-audit authority

- src/api/utils.js
This changes the list ordering in the user app. One thing that I am little unsure about is how I am setting the order for the user-lists: `order: ['firstName:asc', 'surname:asc']`...
This type of usage is not documented ([see docs](https://docs.dhis2.org/master/en/developer/html/dhis2_developer_manual_full.html#webapi_browsing_the_web_api)) but it does work.
I wouldn't really know how to do it in another way, because adding a second order query parameter via the d2 api get method would mean creating an object with duplicate keys.
I tried to start a discussion in the webapi Slack channel to get confirmation about the method I've used, but nobody replied....
> DHIS2-6498: User list should be ordered by first name, last name

- src/index.js
There was a regression after https://github.com/dhis2/user-app/pull/57 which broke translations in the old d2-ui components.
Now we are taking the following steps, which seems to work:
- First set config.baseUrl directly, this makes the first call to getUserSettings work, because that looks at the `preInitConfig.baseUrl`
- Secondly add the translation sources from the app to d2 config object, so they can be applied correctly when d2 initializes
- And lastly `d2.init` is called with that config object
> fix: translations

- src/components/SectionLoader.js
- src/utils/validators.js
Some auto-formatting happened here during the pre-commit hook. The file of interest is `src/utils/validators.js`
> fix(user-form): allow uppercase email addresses (V32 BACKPORT)

- src/constants/queryFields.js
- The User App uses `d2`
- In edit mode, the `userRole` and `userGroup` forms are triggering a `PUT` request via `d2`:
- The `userRole` form triggers the `api.update` method
- The `userGroup` form triggers `userGroup.save`
- One of the above auto-appends `mergeMode=REPLACE`, but this is the default, so the behaviour of both is identical.
- When doing a PUT requests, the webapi will clear the values from the "owned" fields that are not included in the payload.
- To prevent this behaviour, we can always include all `:owned` fields in the GET request field filter and PUT payload <sup>[*](#footnote_1)</sup>.
- Since `authorities` and `displayName` were not technically "owned" fields, they had to be added explicitly.
- I did not have to touch the UserForm, because that was already using the …
> fix: include all owned fields when getting group and role

- src/components/ReplicateUserForm.js
Despite having set autocomplete to "off" on the form, Chrome was still happily filling both the username **and the password** field. 
For the password field, this makes sense because the field-name is `password`. And it's quite well documented that browsers will ignore `autocomplete="off"` for these.... So this was just an oversight from me...
The fact that the username was also being pre-filled was a bit of a mystery too me.... I found [this stackoverflow post](https://stackoverflow.com/questions/12374442/chrome-ignores-autocomplete-off), which mentioned:
> In my experience, Chrome only autocompletes the first <input type="password"> *and the previous <input>*.
This could be the reason why the username field was being autofilled too....
In any case, I decided to add …
> fix(replicate-user): add autocomplete="new-password" to prevent autofill

- i18n/en.pot
- src/components/AuthorityEditor/utils/authorityGroupNames.js
- src/components/AuthorityEditor/utils/groupAuthorities.js
I'm pretty sure I've interpreted and fixed this issue correctly. However, I did make quite a few assumptions which should still be confirmed by @larshelge, see [this issue comment](https://jira.dhis2.org/browse/DHIS2-8148?focusedCommentId=30875&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-30875).
- The Report table and Chart authority are gone
- The Visualizations authority has been added
Since the endpoint is still returning the old authorities I needed to explicitly ignore them
> fix(authorities): add visualization and remove report-table and chart

- package.json
- yarn.lock
Relates to DHIS2-7698
This PR updates the d2-ui library from 29.0.34 to 29.0.35, which has a quick fix for the Indonesian locale with underscore.
> fix(translation): prevent JS error in list view for Indonesian language

- src/api/utils.js
This is a fix that resolves an issue in a workaround, so I guess a little explanation will help 🤦‍♂ 
Originally we had a problem with some fields being cleared that hadn't been touched (or actually weren't even on the form), when updating a user. This problem is due to the fact that we are doing a PUT request here. A PATCH would have been a much better fit, but since the users resource has limited support for PATCH this was a no-go. 
So to fix the original problem, I just looped through all the user fields and appended missing user-properties to the form object from the user object.
There was a problem in the condition I was originally using: I was using this condition to identify user-fields that needed to be appended to the form: `user[ownedPropName] && !data[ownedPropName]`. But if the …
> fix(user): allow clearing string values

- src/containers/UserForm/config.js
- src/utils/fieldRenderers.js
This fix makes the `uiLocale` and `dbLocale` mandatory and prevents the selects from being cleared when tabbing over them. This will prevent the errors from happening under normal circumstances, but a server-side fix is needed to completely fix this issue.
See Slack for some details about this issue https://dhis2.slack.com/archives/CPGUFVC56/p1586163586145200
You could say that there are 3 parts to fixing this completely, and the current PR fixes 1 and 2:
1. Prevent Selects from being cleared when tabbing over them. This was happening because I was spreading the `input` prop on the Select and the `onBlur` and `onFocus` handlers were causing issues, and were not really required to begin with. **This is fixed in the current PR**, see `src/utils/fieldRenderers.js`.
2. Make keyUiLocale and …
> fix(user): make ui and db locale field required and prevent clear onBlur

- src/constants/routeConfig.js
- src/containers/UserForm/config.js
Disclaimer:
I couldn't really think of a fully reliable way to find _all static strings_. I attempted doing a generic search on quotation marks but that yielded way too many results to be useful. So instead I just did some case-insensitive searches for words that may signal a translatable string. I tried `label`, `description`, `name`, `displayname`,  `msg` and `message`....
I found 5 strings that needed to become translatable, but cannot be sure I've caught them all. If you can think of a more reliable way to identify them, please let me know and I'll take another stab at this.
> fix: identified static strings and made them translatable

- i18n/en.pot
- package.json
Updated `.pot` files for this app were created during the build, but these files actually do need to be committed for the transifex workflow. So I am now generating and staging them in the pre-commit husky hook.
> fix(translations): produce and stage pot files in pre-commit hook

- src/components/AuthorityEditor/AuthorityEditor.js
- src/components/AuthorityEditor/AuthorityItem.js
- src/components/AuthorityEditor/AuthoritySection.js
This PR adds some functionality as requested in [JIRA issue DHIS2-7610](https://jira.dhis2.org/browse/DHIS2-7610), but it also removes a lot of code. 
The problem with this component is that it's pretty heavy on the browser. There is quite a lot of data manipulation going on before the component can actually be rendered, but in actual fact the problem lies mainly the fact that a lot of MUI checkboxes need to be rendered with their ripple animations etc...
In the past I have tried to improve performance by using "batched rendering" and also by including quite a few `shouldComponentUpdate` hooks (this hook has now become deprecated). This was quite a while ago, and when reading my own code again, I found that it had all become overly complex. When trying to implement the feature I also ran …
> feat(authority-editor): remove performance hacks, add section checkboxes

- i18n/en.pot
- src/components/DetailSummary.js
This is a follow-up on https://github.com/dhis2/user-app/pull/480 because the testers found one string that wasn't translatable. 
The branch name and and first commit message could be a bit confusing. There were actually two things going wrong:
- Before this fix I was trying to combine a client-side-translated string ("Edit") with what I thought was a server-side-translated string (i.e. user / user-group / user-role)
- To do this I was using a template literal, when I should have been using the i18n interpolation syntax.
- However, after I fixed that in https://github.com/dhis2/user-app/commit/fb4614dd1a6cf2d3dda86cd14f8340a4b3c45c96, I noticed that actually the `baseName` wasn't a server-side-translated string at all. Its value was just one of the constants from …
> fix(i18n): correct edit button text on DetailSummary

- src/api/utils.js
When porting to the app platform, the d2 dependency also got bumped a few minor versions. The newer version didn't include the `generateUid` helper anymore, and I was relying on this helper when creating a user. 
I'm not fully sure why I was generating uids in the client in the first place, I suspect it was needed at some point to ensure the `userCredentials` would be linked to the user correctly 🤷‍♂️ . In any case, I have simply removed the import and am not sending any IDs when POSTing. This seems to work fine: even without these IDs the `user` and `userCredentials` seem to be linked together just fine. I have verified that by checking that the value for a certain field called _"Available dimension restrictions for data analytics"_ (under _"more options"_) is correctly persisted. This …
> fix(user): remove generateUid import and remove ids from POST payload

- src/api/utils.js
This is a super interesting demo of how `d2`s schema based behaviour works:
- There was a schema change on the `displayName` field:
- 2.35dev => `"writable": true` [see 2.35 user schema](https://play.dhis2.org/2.35dev/api/schemas/user.json?fields=klass,displayName,properties[name,writable])
- dev => `"writable": false` [see dev user schema](https://play.dhis2.org/dev/api/schemas/user.json?fields=klass,displayName,properties[name,writable])
- I was iterating through a `d2` `ModelCollection` of users and appending the `username` to the `displayName` before I fed this into the d2-ui `GroupEditor`
- But after this schema change d2 refuses to do this and will throw an error saying:
`TypeError: Cannot set property displayName of #<Model> which has only a getter`
- Luckily the `GroupEditor` …
> fix(group-editor): convert d2 Model to object before setting displayName

- i18n/en.pot
- src/api/index.js
- src/components/List/List.js
- src/containers/GroupList/GroupList.js
- src/selectors/index.js
- src/utils/detectCurrentUserChanges.js
This fixes a critical issue which occurred when loading the Users app in an instance containing 10s of thousands of users.  
This was caused by d2 overeagerly downloading all userGroups (including all their member users) for the current user when using the `d2.currentUser.getUserGroups()` method.  Since this app only ever used the `id` of the groups to determine membership, we can instead only download `userGroups[id]` from the `me` endpoint.  I went ahead and did the same for `userRoles` and removed a duplicated `organisationUnits` fetched by `me` and later from `/api/organisationUnits` - `userGroups` and `userRoles` and `organisationUnits` are all ignored by the d2 `currentUser` constructor (unless `getUserGroups` or `getUserRoles` is called), so this should be safe.
The design of …
> fix: don't fetch unpaged members of current user groups (DHIS2-10377)

- src/selectors/index.js
> fix(expiry date): do not parse empty initial state to date

- package.json
`i18n` was broken on the v35 branch. Upon inspection the issue was identical to https://github.com/dhis2/scheduler-app/pull/164.
@ismay, would you mind merging this in yourself? I'm taking the rest of the day off.
> fix(i18n): generate translations under the default namespace

- src/api/index.js
Fixes [Users with spaces in their usernames cannot be edited](https://jira.dhis2.org/browse/DHIS2-11528) - but I think **users with spaces in their usernames will still not be able to log in.** I think that's another issue with the login process
As of `d2` v31.3.0, the d2 API [handles URI encoding](https://github.com/dhis2/d2/commit/dd5203dd749254608e44e50cfd4200026f0becee#diff-6c0bd5dbc361d2b0c60228112b5dee87b6bc82e9818b31745588ee4b7b6fd1a4), and any encoding done before that causes the error seen in the associated bug report. Maybe that change to `d2` should have incremented the major version?
This PR also fixes the same bug if someone tries to edit the interface or database language of user with spaces in their username
v36 backport: #791 
Versions v35 and v34 don't exhibit this bug …
> fix: leave URI encoding to d2 API

- src/api/index.js
> fix: leave URI encoding to d2 API (v36)

- i18n/en.pot
- src/api/index.js
- src/containers/UserForm/UserForm.js
- src/containers/UserForm/config.js
Closes https://jira.dhis2.org/browse/DHIS2-12046
Adds a single select field for setting the max org unit level for data output to the user form. The field is located under the "Search org units" section in the add and edit user screen, i.e. behind the "More options" part.
> feat(user-form): add max org unit level for data output option

- src/components/UserForm/BasicInformationSection.js
Fixes a typo where the email field is always set as required if the server has the capability to invite users.
> fix(user): only set email field as required if inviting by email

- src/attributes.js
Closes https://jira.dhis2.org/browse/DHIS2-13003
Attribute fields powered by React Final Form are given field names in the format `attributeValues.<attribute ID>` (e.g. `<Field name="attributeValues.oXD88WWSQpR" />`). On form submission, Final Form creates a `values` object containing values for fields that had an `initialValue` prop or were modified.
If no attribute was modified, then the object `values.attributeValues` will not exist and `values.attributeValues[attribute.id]` will throw an error. This PR fixes this issue by using optional chaining.
> fix(attributes): don't assume presence of values.attributeValues

- package.json
- yarn.lock
I've update the username validator in @dhis2/ui to allow hypens, and the backend is doing this as well. There was a mistake in the backend, so that solution still needs to be reworked. Since the client is currently a bit more strict than the server, I don't think that should impact testing....
So the new behaviour is that:
- Hyphens (`-`) are now allowed in a username
- A username cannot start or end with a hyphen
- Repeating hyphens (`--`) are not allowed
You could test this out by going to the `/#/users/new` route and see what happens in the username field.
Some related JIRA issues:
- [DHIS2-13824](https://dhis2.atlassian.net/browse/DHIS2-13824) (current issue)
- [DHIS2-13768](https://dhis2.atlassian.net/browse/DHIS2-13768) (backend, not completely right)
- …
> fix: upgrade @dhis2/ui to use correct username validation

- src/components/BulkMemberManager/BulkMemberManager.js
- src/components/BulkMemberManager/ResultsTable/ResultsTable.js
- src/components/BulkMemberManager/hooks/useResults/useResults.js
Fixes [DHIS2-13914](https://dhis2.atlassian.net/browse/DHIS2-13914)
What I've addressed here is the following:
- It was possible to end up with duplicate items in the list on the right
- The button to bulk add items to the list to the right was sometimes visible when it shouldn't have been
- The toggle-all-checkbox would sometimes not have the correct selection/disabled state
All of the above was related to the fact that "selected results" and "pending changes" are separate things and should be handled differently, depending on the context.
@cooper-joe could you review the current implementation?
> fix: user manager checkbox behaviour

- src/components/UserForm/validators.js
- src/pages/UserList/ContextMenu/Modals/ReplicateModal.js
- src/pages/UserList/UserTable.test.js
Fixes [DHIS2-14147](https://dhis2.atlassian.net/browse/DHIS2-14147)
Whilst migrating the username check to the new endpoint, I realised the username uniqueness check in the replicate user dialog had been removed during a previous refactor. Once I had added that validator I realised the loading state was not showing while the async validation was running, so I also updated the input components there....
> fix: use dedicated endpoint for checking the username

- i18n/en.pot
- src/components/BulkMemberManager/BulkMemberManager.module.css
- src/components/BulkMemberManager/ResultsTable/ResultsTableRow.js
- src/components/BulkMemberManager/ResultsTable/ResultsTableRow.module.css
- src/components/Form.js
- src/components/UserForm/InviteUserSection.js
- src/components/UserForm/UserForm.js
- src/pages/UserList/ContextMenu/ContextMenu.js
- src/pages/UserList/ContextMenu/Modals/ResetPasswordModal.js
- src/pages/UserList/UserTable.js
- src/pages/UserList/UserTable.test.js
Fixes:
- [DHIS2-13425](https://dhis2.atlassian.net/browse/DHIS2-13425): Renamed the user table column from ""Account disabled?" to "status" and now populating each row with "Active" or "Disabled" text.
- [DHIS2-12910](https://dhis2.atlassian.net/browse/DHIS2-12910): Changed the button texts below the "create user form" when inviting a user by email*.
- [DHIS2-13424](https://dhis2.atlassian.net/browse/DHIS2-13424): Tweaked the texts in the reset password dialog - this dialog can be opened via the context menu in the user table *.
- [DHIS2-14064](https://dhis2.atlassian.net/browse/DHIS2-14064): Gave the bulk user manager - in the create/edit user-group form - some more width, but still kept a max-width with very wide monitors in mind. I also added some extra whitespace to the last column to …
> fix: address various style and text issues

- i18n/en.pot
- src/utils/validators.js
Addresses this [DHIS2-14793](https://dhis2.atlassian.net/browse/DHIS2-14793) (from a CoP post)
**After**
Note: the modern version of the users app also lacks a validator for first name, but upon attempting to save, the error will be displayed on the field. We could update this as well (but it's not requested directly by the ticket)
[DHIS2-14793]: https://dhis2.atlassian.net/browse/DHIS2-14793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add first name validator (v37) [DHIS2-14793]

- i18n/en.pot
- src/utils/validators.js
Sorry; I did not read the [ticket](https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-14793) close enough. While the original CoP post was about adding a validator on the first name, Gassim pointed out on the ticket that this also applies for surname, so we should add a validator there too.
**Before**
**After**
> fix: add surname validator (v37) [DHIS2-14793]

- src/components/UserForm/RolesSection.js
See https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-15368
Front end expects response from api/user/{uid} to contain an object `userCredentials` which contains an array `userRoles`. However, when there are no `userRoles`, `userCredentials` does not contain the property `userRoles`, and hence causes the app to crash (tries to map non-existent `userRoles` array)
This arguably might be something the backend should change, but updating the front-end also is sufficient for the immediate purpose of stopping the app from crashing.
Note: we decided in our meeting on 20 June that we would fix this on the front end and backend team will evaluate if they also want to do anything here.
> fix: handle empty user roles response [DHIS2-15368]

- src/pages/UserList/ContextMenu/ContextMenu.js
See https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-15354.
This issue was fixed in versions 39+ by this PR: https://github.com/dhis2/user-app/pull/924. This PR effectively backports that change to v38.
(Note in before "Reset password" option is displayed for https://debug.dhis2.org/2.38, whereas it's hidden in after. It should be hidden because email is not configured for this instance)
**Before**
**After**
> fix: hide reset password [DHIS2-15354]

- src/components/SearchableOrgUnitTree/AsyncAutoComplete/useOrgUnitSearchResults.js
See https://dhis2.atlassian.net/browse/DHIS2-14585
We have a typo in an apparent typo in our org unit filter logic in the user app that is prevent matches not at the beginning of the string to match.
In addition, I saw that we were looking for matches on `name`, whereas we should use `displayName` (i.e. to match based on the user's currently selected UI locale)
**Before**
**After**
> fix: org unit search logic [DHIS2-14585]

- src/pages/UserList/ContextMenu/Modals/DisableModal.js
- src/pages/UserList/ContextMenu/Modals/EnableModal.js
See [DHIS2-15512](https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-15512). v40+ already updated to json-patch for enable/disable from the context menu, but this was not applied for v38 and v39. This fix is for v38 (where the bug was reported), and could be then forward ported to v39
**Before**
**After**
[DHIS2-15512]: https://dhis2.atlassian.net/browse/DHIS2-15512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: enable disable functionality

- src/components/UserForm/getUserData.js
See [DHIS2-15359](https://dhis2.atlassian.net/browse/DHIS2-15359). Currently we update accountExpiry in useCredentials but it's also a property on the main payload. Since it occurs in both places (but is inconsistent), it does not get cleared out when it is removed. Morten Svænes looked at this on the backend and thought we could either update in both places or refactor to use PATCH. I'm just updating in both parts of the payload as I think that is simpler for just a bug fix.
**Before**
**After**
[DHIS2-15359]: https://dhis2.atlassian.net/browse/DHIS2-15359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: account expiry clear

- src/AppWrapper.js
- src/components/Form.js
- src/components/GroupForm/GroupForm.js
- src/components/RoleForm/RoleForm.js
- src/components/UserForm/UserForm.js
- src/pages/GroupList/ContextMenu/ContextMenu.js
- src/pages/GroupList/GroupTable.js
- src/pages/RoleList/ContextMenu/ContextMenu.js
- src/pages/RoleList/RoleTable.js
- src/pages/UserList/ContextMenu/ContextMenu.js
- src/pages/UserList/UserTable.js
- src/providers/ReferrerContext.js
- src/providers/ReferrerProvider.js
- src/providers/index.js
- src/providers/useReferrer.js
- src/utils/navigateTo.js
I noticed when making some updates in the user app that the redirects after saving a user group or user role did not appear to work (this might be limited to the case of editing a user group/user role related to the current user). Moreover, since they were using `history.goBack()` when successful, these redirects would navigate to the page you were previously on rather than the main menu for the relevant user metadata (users, user groups, or user roles). Since we use deep links, this behaviour seems counter-intuitive (e.g. if I am on dhis2.org and navigate to a user edit page and save, I think this should when successful go to the list of users, not back to dhis2.org)
I have used our internal `navigateTo` function which is using history.push()
> fix: update successful save redirects [DHIS2-15431]

- i18n/en.pot
- src/components/BulkMemberManager/BulkMemberManager.module.css
- src/components/BulkMemberManager/ResultsTable/ResultsTableRow.js
- src/components/BulkMemberManager/ResultsTable/ResultsTableRow.module.css
- src/components/Form.js
- src/components/UserForm/InviteUserSection.js
- src/components/UserForm/UserForm.js
- src/pages/GroupList/ContextMenu/ContextMenu.js
- src/pages/RoleList/ContextMenu/ContextMenu.js
- src/pages/UserList/ContextMenu/ContextMenu.js
- src/pages/UserList/ContextMenu/Modals/ResetPasswordModal.js
- src/pages/UserList/UserTable.js
- src/pages/UserList/UserTable.test.js
see https://dhis2.atlassian.net/browse/DHIS2-15524
This PR cherry picks changes to catch up some bugs/UI changes unaddressed in v39:
- User creation via email invite has buttons "Send invite"/"Cancel invite"
- the reset password text is updated (removes possessive with s)
- user with all authority can now see 'reset password' option in user context menu 
- context menu will now close when a modal is closed
- user list has "status" column (with active/disabled) instead of 'Account disabled?' column
- bulk user editor can expand to 1800px width (rather than 900px)
> fix: catch up fixes v39 [DHIS2-15524]

- i18n/en.pot
- src/components/Form.js
- src/components/UserForm/InviteUserSection.js
- src/components/UserForm/UserForm.js
- src/pages/GroupList/ContextMenu/ContextMenu.js
- src/pages/RoleList/ContextMenu/ContextMenu.js
- src/pages/UserList/ContextMenu/ContextMenu.js
- src/pages/UserList/ContextMenu/Modals/ResetPasswordModal.js
- src/pages/UserList/UserTable.js
- src/pages/UserList/UserTable.test.js
see https://dhis2.atlassian.net/browse/DHIS2-15524
This PR cherry picks changes to catch up some bugs/UI changes unaddressed in v38:
- User creation via email invite has buttons "Send invite"/"Cancel invite"
- the reset password text is updated (removes possessive with s)
- user with all authority can now see 'reset password' option in user context menu 
- context menu will now close when a modal is closed
- user list has "status" column (with active/disabled) instead of 'Account disabled?' column
Note that one of the items on the ticket (expanded maximum width for bulk user edit) does not apply in v38 and is hence not included here.
> fix: catch up fixes v38 [DHIS2-15524]

- src/components/SearchableOrgUnitTree/AsyncAutoComplete/getRestrictedOrgUnits.js
- src/components/SearchableOrgUnitTree/AsyncAutoComplete/getRestrictedOrgUnits.test.js
This fixes an issue where organisation units were not appearing in search results because the user was deemed not to have access to the organisation unit. **Note: this issue was for users without ALL authority** (e.g. `admin` on our play instances)
Issue was that the code was assuming that api/me returned an array of orgUnit ids, but instead we are getting an array of objects like [{id: "someOrgUnit"}] (maybe this was an api change at some point?)
**Before**
**After**
(P.S. I noticed another bug that if you have clicked on multiple of these org unit selection search fields, the search results will appear in all of them, but I don't want to look at/fix that here)
> fix: org unit access in search [DHIS2-16268]

- i18n/en.pot
- src/components/GroupForm/BasicInformationSection.js
- src/components/GroupForm/GroupForm.js
- src/components/GroupForm/UserGroupManagementSection.js
- src/components/GroupForm/createRequestBody.js
- src/components/GroupForm/validators.js
The user app's User Group form got refactored in v39 to add bulk user management and at that time it was also amended to use json+patch api.
The user group managedGroups users appears only to work with the json+patch, so I have replicated the v39 changes to UserGroup form in v38 (except for the bulk user management).
On the downside, the code updates do not seem to work (but this bug with not being able to update user group code also exists on v41, v40, v39, so I think merging the change here and then fixing the code update issue is probably better?). UPDATE: Viet is working on a fix for that issue (https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-16299?)
> fix: update user group form (v38) [DHIS2-12294]

- i18n/en.pot
- src/components/RoleForm/groupAuthorities/metadata.js
Backport of https://github.com/dhis2/user-app/pull/1339
> fix: add missing authority translations [DHIS2-16516]

- i18n/en.pot
- src/components/GroupForm/createRequestBody.js
I made an update for https://github.com/dhis2/user-app/pull/1328 to backport some changes for user group form (and to fix a bug where one could not edit groups assigned to user groups).
However, the code I backported had references to members (which are not editable on v38 because bulk member edit is not a feature there). As a result, an error occurred when saving a new user group ([DHIS2-16766](https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-16766))
This PR removes the references to members on user group add and edit (the code for edit didn't do anything because there is no members field in the form).
I've tested to confirm that I can create a new user group and edit the user group management for existing user groups
[DHIS2-16766]: …
> fix: remove members references from user group form [DHIS2-16766]

- .github/workflows/dhis2-verify-app.yml
- d2.config.js
- package.json
This PR sets up the user-app for continuous release
> chore: continuous release setup

- i18n/en.pot
- src/components/DetailSummary.js
Implements [Jira ticket](https://dhis2.atlassian.net/browse/DHIS2-12079)
---
Implemented a modification to the `renderPropertyFields` function on the group details page to render only the ID field on user group page and its corresponding value.
---
-   [ ] None
---
-   [ ] API docs are generated
-   [ ] Tests were added
-   [ ] Storybook demos were added
_All points above should be relevant for feature PRs. For bugfixes, some points might not be relevant. In that case, just check them anyway to signal the work is done._
---
> fix: update user group details update

- src/components/GroupForm/BulkUserManager/useQueries.js
Implements [DHIS2-16958](https://dhis2.atlassian.net/browse/DHIS2-16958)
---
Implemented a modification to the query used to search users in a user group.
This is a backport from another [PR](https://github.com/dhis2/user-app/pull/1365)
---
-   [ ] None
---
-   [ ] API docs are generated
-   [ ] Tests were added
-   [ ] Storybook demos were added
_All points above should be relevant for feature PRs. For bugfixes, some points might not be relevant. In that case, just check them anyway to signal the work is done._
---
[DHIS2-16958]: https://dhis2.atlassian.net/browse/DHIS2-16958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: change query for user search in user groups

- i18n/en.pot
- src/pages/GroupDetails/GroupDetails.js
Implements [DHIS2-17083](https://dhis2.atlassian.net/browse/DHIS2-17083)
---
conditionally display update status in user group details page based on access levels
---
-   [ ] None
---
-   [ ] API docs are generated
-   [ ] Tests were added
-   [ ] Storybook demos were added
_All points above should be relevant for feature PRs. For bugfixes, some points might not be relevant. In that case, just check them anyway to signal the work is done._
---
[DHIS2-17083]: https://dhis2.atlassian.net/browse/DHIS2-17083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add a default notice box based on access level of the user

- src/components/RoleForm/groupAuthorities/groupAuthorities.js
Fixes [DHIS2-10843](https://dhis2.atlassian.net/browse/DHIS2-10843).
Authorities are now sorted ignoring case as per image below
[DHIS2-10843]: https://dhis2.atlassian.net/browse/DHIS2-10843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: ignore case when sorting grouped authorities by name

- src/components/RoleForm/groupAuthorities/groupAuthorities.js
Adds the `F_CAPTURE_DATASTORE_UPDATE` to the tracker authority list.
> fix: add capture authority to tracker list

- i18n/en.pot
- src/pages/UserList/ContextMenu/ContextMenu.js
- src/pages/UserList/ContextMenu/ContextMenu.test.js
- src/pages/UserList/ContextMenu/Modals/ResetTwoFAModal.js
- src/pages/UserList/ContextMenu/Modals/ResetTwoFAModal.module.css
See ticket [DHIS2-18831](https://dhis2.atlassian.net/browse/DHIS2-18831)
This ended up being more of a bug fix than a feature because it turns out we already had a reset two factor authentication item in the context menu. However, we were checking for user.twoFactorEnabled which does not exist on the user object, so we were not displaying it.
After discussion with Morten, we've decided that we will not be exposing information on whether a user has two factor authentication enabled as that could potentially be a security issue to disclose that information more broadly (in the sense that not everyone has a need to know if users have two factor authentication enabled).
As a result, I am updating the app to always display this "Reset two factor authentication" option with some more …
> fix: reset 2fa button [DHIS2-18831]

- i18n/en.pot
- src/pages/UserList/ContextMenu/ContextMenu.js
- src/pages/UserList/ContextMenu/ContextMenu.test.js
- src/pages/UserList/ContextMenu/Modals/ResetTwoFAModal.js
- src/pages/UserList/ContextMenu/Modals/ResetTwoFAModal.module.css
v40 backport for https://github.com/dhis2/user-app/pull/1530
> fix: reset 2fa button [DHIS2-18831] (#1530)

- src/components/RoleForm/MetadataAuthoritiesTable.js
- src/components/RoleForm/MetadataAuthoritiesTable.test.js
See https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-19009?jql=project%20%3D%20%22DHIS2%22%20ORDER%20BY%20created%20DESC
As agreed (https://dhis2.atlassian.net/browse/DHIS2-19009?focusedCommentId=209341): this updates the functionality of the "Select all" checkboxes to be disabled when there is a filter. Note that you can first select all, then add a filter and then the checkbox will be disabled, so to unselect everything, you'd have to clear the filter.
I think the UI could still be improved here, but hopefully this is some improvement.
I've also added a tooltip to explain why the checkboxes are disabled:
> fix: disable authority select all when there is a filter [DHIS2-19009]

- src/providers/system/SystemProvider.jsx
- src/providers/system/useSystemInformation.test.js
See https://dhis2.atlassian.net/browse/DHIS2-19234
Morten and Jan requested that `F_PREVIOUS_IMPERSONATOR_AUTHORITY` be filtered out as it's not an authority users should add to user roles.
I have added logic to filter it out. Filtering it out means that it will appear in the "legacy authorities" section if you had added previously.
The `F_PREVIOUS_IMPERSONATOR_AUTHORITY` is in v41 and v42, so there's no needed feature toggling here.
**Before**
**After**
_when in edit mode_
Manually tested and added some automated tests to check that the authority is filtered out of the authorities provider/useSystemInformation hook.
You can also create a user role with `F_PREVIOUS_IMPERSONATOR_AUTHORITY`/`User Impersonation (switch back)` in normal user app and then check that the role has …
> feat: filter out impersonation authority [DHIS2-19324]
